export type ObrigacaoSeed = {
  codigo: string;
  nome: string;
  descricao: string | null;
  esfera: "federal" | "estadual" | "municipal" | "trabalhista";
  periodicidade: "mensal" | "trimestral" | "anual";
  aplicavelA: string[];
  condicaoFlags: string[];
  condicaoModo: "any" | "all";
  ufs: string[];
  cnaePrefixos: string[];
  vencDia: number;
  vencMesOffset: number;
  vencMes: number | null;
  vencAnoOffset: number;
  prazoInternoDiasUteis: number;
  antecipa: boolean;
  ordem: number;
};

const SIMPLES = ["simples_sem_func", "simples_com_func"];

export const MATRIZ_PADRAO: ObrigacaoSeed[] = [
  {
    codigo: "DASN-SIMEI",
    nome: "DASN-SIMEI",
    descricao: "Declaração anual do MEI.",
    esfera: "federal",
    periodicidade: "anual",
    aplicavelA: ["mei"],
    condicaoFlags: [],
    condicaoModo: "any",
    ufs: [],
    cnaePrefixos: [],
    vencDia: 31,
    vencMesOffset: 1,
    vencMes: 5,
    vencAnoOffset: 1,
    prazoInternoDiasUteis: 0,
    antecipa: true,
    ordem: 10,
  },
  {
    codigo: "PGDAS-D",
    nome: "PGDAS-D",
    descricao: "Apuração mensal do Simples Nacional.",
    esfera: "federal",
    periodicidade: "mensal",
    aplicavelA: SIMPLES,
    condicaoFlags: [],
    condicaoModo: "any",
    ufs: [],
    cnaePrefixos: [],
    vencDia: 20,
    vencMesOffset: 1,
    vencMes: null,
    vencAnoOffset: 1,
    prazoInternoDiasUteis: 0,
    antecipa: true,
    ordem: 20,
  },
  {
    codigo: "DEFIS",
    nome: "DEFIS",
    descricao: "Declaração de Informações Socioeconômicas e Fiscais.",
    esfera: "federal",
    periodicidade: "anual",
    aplicavelA: SIMPLES,
    condicaoFlags: [],
    condicaoModo: "any",
    ufs: [],
    cnaePrefixos: [],
    vencDia: 31,
    vencMesOffset: 1,
    vencMes: 3,
    vencAnoOffset: 1,
    prazoInternoDiasUteis: 0,
    antecipa: true,
    ordem: 30,
  },
  {
    codigo: "DCTFWEB",
    nome: "DCTFWeb",
    descricao: "Declaração de débitos previdenciários.",
    esfera: "federal",
    periodicidade: "mensal",
    aplicavelA: ["*"],
    condicaoFlags: ["tem_folha"],
    condicaoModo: "any",
    ufs: [],
    cnaePrefixos: [],
    vencDia: 20,
    vencMesOffset: 1,
    vencMes: null,
    vencAnoOffset: 1,
    prazoInternoDiasUteis: 0,
    antecipa: true,
    ordem: 40,
  },
  {
    codigo: "FGTS-DIGITAL",
    nome: "FGTS Digital",
    descricao: "Recolhimento do FGTS.",
    esfera: "trabalhista",
    periodicidade: "mensal",
    aplicavelA: ["*"],
    condicaoFlags: ["tem_folha"],
    condicaoModo: "any",
    ufs: [],
    cnaePrefixos: [],
    vencDia: 20,
    vencMesOffset: 1,
    vencMes: null,
    vencAnoOffset: 1,
    prazoInternoDiasUteis: 0,
    antecipa: true,
    ordem: 50,
  },
  {
    codigo: "EFD-CONTRIB",
    nome: "EFD-Contribuições",
    descricao: "PIS/COFINS.",
    esfera: "federal",
    periodicidade: "mensal",
    aplicavelA: ["presumido_real"],
    condicaoFlags: [],
    condicaoModo: "any",
    ufs: [],
    cnaePrefixos: [],
    vencDia: 15,
    vencMesOffset: 2,
    vencMes: null,
    vencAnoOffset: 1,
    prazoInternoDiasUteis: 0,
    antecipa: true,
    ordem: 60,
  },
  {
    codigo: "EFD-REINF",
    nome: "EFD-Reinf",
    descricao: "Retenções e informações da contribuição previdenciária.",
    esfera: "federal",
    periodicidade: "mensal",
    aplicavelA: ["presumido_real"],
    condicaoFlags: [],
    condicaoModo: "any",
    ufs: [],
    cnaePrefixos: [],
    vencDia: 15,
    vencMesOffset: 1,
    vencMes: null,
    vencAnoOffset: 1,
    prazoInternoDiasUteis: 0,
    antecipa: true,
    ordem: 70,
  },
  {
    codigo: "ECD",
    nome: "ECD",
    descricao: "Escrituração Contábil Digital.",
    esfera: "federal",
    periodicidade: "anual",
    aplicavelA: ["presumido_real"],
    condicaoFlags: [],
    condicaoModo: "any",
    ufs: [],
    cnaePrefixos: [],
    vencDia: 31,
    vencMesOffset: 1,
    vencMes: 5,
    vencAnoOffset: 1,
    prazoInternoDiasUteis: 0,
    antecipa: true,
    ordem: 80,
  },
  {
    codigo: "ECF",
    nome: "ECF",
    descricao: "Escrituração Contábil Fiscal.",
    esfera: "federal",
    periodicidade: "anual",
    aplicavelA: ["presumido_real"],
    condicaoFlags: [],
    condicaoModo: "any",
    ufs: [],
    cnaePrefixos: [],
    vencDia: 31,
    vencMesOffset: 1,
    vencMes: 7,
    vencAnoOffset: 1,
    prazoInternoDiasUteis: 0,
    antecipa: true,
    ordem: 90,
  },
];
